[versions]
# Minecraft
minecraft = "1.21"

# Fabric
fabric-yarn = "1.21+build.9"
fabric-loader = "0.15.11"
fabric-loom = "1.7-SNAPSHOT"
fabric-api = "0.100.7+1.21"

# Library
gson = "2.11.0"
lombok = "1.18.34"


[libraries]
# Minecraft
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Fabirc
fabric-yarn = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

# Library
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }


[plugins]
# Fabric
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
